# Generated by Django 5.0.6 on 2024-05-30 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=200, unique=True)),
                ('nom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=15)),
                ('sexe', models.CharField(max_length=2)),
                ('emails', models.EmailField(max_length=254)),
                ('date_naissance', models.DateField(blank=True)),
                ('lieu_naissance', models.CharField(max_length=200)),
                ('cni', models.CharField(max_length=14)),
                ('lieu_residence', models.CharField(max_length=150)),
                ('civilite', models.CharField(max_length=200)),
                ('nombre_enf', models.IntegerField(default=0)),
                ('nationalite', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=12)),
                ('profession', models.CharField(max_length=12)),
                ('diplome', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('statut', models.CharField(blank=True, default='active', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departement', to='gestionAdministration.employe')),
            ],
        ),
        migrations.CreateModel(
            name='ContratArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=200)),
                ('types', models.CharField(max_length=200)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dateSignature', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('motif', models.CharField(max_length=100)),
                ('date_archive', models.DateField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats_archive', to='gestionAdministration.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=200)),
                ('types', models.CharField(max_length=200)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dateSignature', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, default='encours', max_length=200)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='gestionAdministration.employe')),
            ],
        ),
    ]
