# Generated by Django 5.0.6 on 2024-05-30 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAdministration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAdministration.employe'),
        ),
    ]
