# Generated by Django 5.0.6 on 2024-05-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAdministration', '0003_evenement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('lieu', models.CharField(max_length=100)),
                ('date_archive', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='evenement',
            name='statut',
            field=models.CharField(default='en attente', max_length=50),
        ),
    ]
