# Generated by Django 5.0.6 on 2024-06-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAdministration', '0004_archiveevent_evenement_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='participant',
            field=models.ManyToManyField(related_name='participant', to='gestionAdministration.employe'),
        ),
    ]
