# Generated by Django 5.0.6 on 2024-06-03 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAdministration', '0005_evenement_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messagess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj', models.CharField(max_length=100)),
                ('contenu', models.TextField()),
                ('fichier', models.FileField(blank=True, null=True, upload_to='media/')),
                ('statut', models.CharField(default='en attente', max_length=100)),
                ('date_envoie', models.DateField(auto_now_add=True)),
                ('emetteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emetteur', to='gestionAdministration.employe')),
                ('recepteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepteur', to='gestionAdministration.employe')),
            ],
        ),
    ]
