# Generated by Django 5.0.6 on 2024-06-04 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAdministration', '0007_alter_messagess_date_envoie'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj', models.CharField(max_length=100)),
                ('contenu', models.TextField()),
                ('fichier', models.FileField(blank=True, null=True, upload_to='media/')),
                ('date_arch', models.DateTimeField(auto_now_add=True)),
                ('emetteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emetteurs', to='gestionAdministration.employe')),
                ('recepteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepteurs', to='gestionAdministration.employe')),
            ],
        ),
    ]
