# Generated by Django 5.0.6 on 2024-06-07 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAdministration', '0008_archivemessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departement',
            name='employe',
        ),
        migrations.AddField(
            model_name='departement',
            name='responsable',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departement', to='gestionAdministration.employe'),
        ),
        migrations.AddField(
            model_name='employe',
            name='depart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionAdministration.departement'),
        ),
    ]
