# Generated by Django 5.0.6 on 2024-07-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAdministration', '0009_remove_departement_employe_departement_responsable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('date_notif', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
