# Generated by Django 5.0.6 on 2024-07-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAdministration', '0010_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='renouvelle',
            field=models.BooleanField(default=False),
        ),
    ]
