# Generated by Django 5.0.6 on 2024-07-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAdministration', '0012_evenement_types_alter_evenement_date_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='types',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
