# Generated by Django 5.0.6 on 2024-07-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAdministration', '0014_conge_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='types',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
