# Generated by Django 5.0.6 on 2024-07-06 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAdministration', '0016_conge_depart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conge',
            name='depart',
        ),
    ]
