# Generated by Django 5.0.6 on 2024-07-07 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAdministration', '0017_remove_conge_depart'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='initiateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiateur', to='gestionAdministration.employe'),
        ),
    ]
