# Generated by Django 5.0.6 on 2024-07-07 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAdministration', '0018_evenement_initiateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagess',
            name='recepteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recepteur', to='gestionAdministration.employe'),
        ),
    ]
