# Generated by Django 5.0.6 on 2024-07-08 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAdministration', '0019_alter_messagess_recepteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='employe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionAdministration.employe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notifications',
            name='date_notif',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='description',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Commentaire',
        ),
    ]
