# Generated by Django 5.0.6 on 2024-07-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAdministration', '0021_notifications_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='avantages',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='confidetialite',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='obligations',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='resialiasion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contratarchive',
            name='avantages',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contratarchive',
            name='confidetialite',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contratarchive',
            name='obligations',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contratarchive',
            name='resialiasion',
            field=models.TextField(null=True),
        ),
    ]
