# Generated by Django 5.0.6 on 2024-07-09 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAdministration', '0022_contrat_avantages_contrat_confidetialite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrat',
            old_name='confidetialite',
            new_name='confidetialites',
        ),
        migrations.RemoveField(
            model_name='contratarchive',
            name='confidetialite',
        ),
    ]
