# Generated by Django 5.0.6 on 2024-07-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAdministration', '0024_remove_contrat_confidetialites'),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='approbation',
            field=models.CharField(default='En attente', max_length=100),
        ),
        migrations.AlterField(
            model_name='conge',
            name='statut',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
