# Generated by Django 5.0 on 2025-01-05 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAdministration', '0025_conge_approbation_alter_conge_statut'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchiveEvent',
        ),
        migrations.AlterField(
            model_name='contratarchive',
            name='dateSignature',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contratarchive',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAdministration.employe'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='statut',
            field=models.CharField(choices=[('en attente', 'En attente'), ('passe', 'Passé'), ('annule', 'Annulé'), ('archivé', 'Archivé')], default='en attente', max_length=50),
        ),
        migrations.DeleteModel(
            name='ArchiveMessage',
        ),
    ]
