# Generated by Django 5.0 on 2025-01-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAdministration', '0026_delete_archiveevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagess',
            name='statut',
            field=models.CharField(choices=[('en attente', 'En attente'), ('reçu', 'Reçu'), ('supprimer', 'Supprimer')], default='en attente', max_length=100),
        ),
    ]
